# Zenburn-ish Foot config
[main]
font=CaskaydiaMono Nerd Font:size=12

[colors-dark]
background=3A3A3A
foreground=DCDCCC
cursor=3A3A3A DCDCCC
selection-background=4F4F4F
selection-foreground=F0DFAF
regular0=1E2320
regular1=D78787
regular2=60B48A
regular3=DFAF8F
regular4=506070
regular5=DC8CC3
regular6=8CD0D3
regular7=DCDCCC
bright0=709080
bright1=DCA3A3
bright2=C3BF9F
bright3=F0DFAF
bright4=94BFF3
bright5=EC93D3
bright6=93E0E3
bright7=FFFFFF

[csd]
preferred=none
